### ISSUE TITLE
Add a Pull Request Template

### ISSUE THREAD

**Issue by uzaxirr** [intelowlproject/go-intelowl#12]
Add up a Pull Request template similar to the one present in [intelOwl](https://github.com/intelowlproject/IntelOwl/blob/master/.github/pull_request_template.md)

**Comment by uzaxirr** [comment]
I can work on this if you could specify what all fields should be emitted or added from [this](https://github.com/intelowlproject/IntelOwl/blob/master/.github/pull_request_template.md) template

**Comment by fear-the-reaper** [comment]
Made a PR please review!
