### ISSUE TITLE
Secure API Token

### ISSUE THREAD

**Issue by uzaxirr** [intelowlproject/go-intelowl#14]
Currently in [gointelowl_test.go](https://github.com/intelowlproject/go-intelowl/blob/main/gointelowl_test.go) the API token are exposed, it is desired to store them in a `.env` file and then use

**Comment by mlodic** [comment]
yeah that is pretty bad

**Comment by uzaxirr** [comment]
Assign this issue to me. i"ll work on this

**Comment by eshaan7** [comment]
The env variables stuff can be managed once we have unittests setup. Ideally it should be handled by some go's testing framework or github workflow file.
