### ISSUE TITLE
[rewrite] Break up into service objects/resources

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/go-intelowl#16]
I don't like approach of just appending functions to the `IntelOwlClient` struct.

This SDK should be created following the approach given in [this](https://medium.com/@marcus.olsson/writing-a-go-client-for-your-restful-api-c193a2f4998c) blog-post, especially the "Service Objects" heading.

This approach is very similar to how we (at Certego) wrote [pydragonfly](https://github.com/certego/pydragonfly) recently using the [django-rest-client](https://github.com/certego/django-rest-client) framework (also written by us).

**Comment by uzaxirr** [comment]
Adding more useful articles for reference

- [Go client library best practices](https://medium.com/@cep21/go-client-library-best-practices-83d877d604ca)

**Comment by 0x0elliot** [comment]
Hey, I would like to take over this issue! If there are any other relevant resources and projects out there that meet your expectations from where you would like me to take inspiration from written specifically in GOLang, please link them here as well! I am a bit new to GOLang but I would like to learn further for this project.

**Comment by 0x0elliot** [comment]
I also feel like the error handling here isn't done very well at the moment. For example, <a href = "https://github.com/intelowlproject/go-intelowl/blob/77be67581b6912372ea8953bc322627b1fc2c069/gointelowl.go#L30">here</a>, `log.Fatalln(err)` would just exit the program. It seems better to handle the errors more gracefully for a library. Maybe we can look into wrapping the errors in the functions/methods as well?

**Comment by eshaan7** [comment]
^Yes, that's the point of the rewrite. The current code (the methods inside the IntelOwlClient struct) are to be completely discarded.

**Comment by 0x0elliot** [comment]
I am in the process of finishing this. Just a heads up!

**Comment by 0x0elliot** [comment]
Kindly review my PR and let me know how I can make it better!

**Comment by eshaan7** [comment]
Defining some basic primitives of what we are looking for.

1. Since we want to use the "Service Objects" pattern, the ideal naming convention would be something like this:

```go
c := IntelOwlClient(opts* IntelOwlClientOptions)
c.Job.List() -> []Job // will not take params because we will hard-code `?paginate=false` URL parameter.
c.Job.Get(id uint64) -> Job
c.Job.Delete(id uint64) -> bool
c.Job.DownloadSample(id uint64) -> []byte // or FileReader object?
c.Job.Kill(id uint64) -> bool
c.Job.Retry(id uint64) -> bool
c.Job.KillAnalyzer(id uint64, analyzerName string) -> bool
c.Job.KillConnector(id uint64, connectorName string) -> bool
c.Job.RetryAnalyzer(id uint64, analyzerName string) -> bool
c.Job.RetryConnector(id uint64, connectorName string) -> bool
c.Tag.List() -> []Tag // does not require URL params
c.Tag.Get(id uint64) -> Tag
c.Tag.Create(params* TagParams) -> Tag
c.Tag.Update(id uint64, params* TagParams) -> Tag
c.Tag.Delete(id uint64) -> bool
c.CreateFileAnalysis(params* FileAnalysisParams) -> AnalysisResponse
c.CreateObservableAnalysis(params* ObservableAnalysisParams) -> AnalysisResponse
c.Analyzer.GetConfigs() -> []AnalyzerConfig
c.Analyzer.HealthCheck(analyzerName string) -> bool
c.Connector.GetConfigs() -> []ConnectorConfig
c.Connector.HealthCheck(connectorName string) -> bool
```

2. We want to provide `struct` definitions for all request parameters and in some cases also the response parameters. For example:

```go
// basic
type IntelOwlClientOptions struct {} // will contain url, token, certificate, etc.
// response
type Tag struct {
    ID uint64 `json:"id"`
    Label string `json:"label"`
    Color  string `json:"color"`
}
type Job struct {} // see JobSerializer on IntelOwl:dev-v4
type AnalysisResponse struct {} // see AnalysisResponseSerializer on IntelOwl:dev-v4
type AnalyzerConfig struct {}
type ConnectorConfig struct {}
// request
type TagParams struct {}
type FileAnalysisParams struct {} //  see FileAnalysisSerializer on IntelOwl:dev-v4
type ObservableAnalysisParams struct {}  // see ObservableAnalysisSerializer on IntelOwl:dev-v4
```

You can also refer to the [pyintelowl.py](https://github.com/intelowlproject/pyintelowl/blob/master/pyintelowl/pyintelowl.py) for request parameters specification.

**Comment by fear-the-reaper** [comment]
# API Endpoints TODO list:
**Tick when merged with master/main**
## Tags
- [x] `GET /api/tags`
- [x] `GET /api/tags/{id}`
- [x] `POST /api/tags/`
- [x] `PUT /api/tags/{id}`
- [x] `DELETE /api/tags/{id}`

## Analyzer
- [x]  `GET /api/get_analyzer_configs`
- [x] `GET /api/analyzer/{NameOfAnalyzer}/healthcheck`

## Connector
- [x]  `GET /api/get_connector_configs`
- [x] `GET /api/connector/{NameOfConnector/healthcheck`

## Job
- [x] `GET /api/jobs`
- [x] `GET /api/jobs/{id}`
- [x] `DELETE /api/jobs/{id}`
- [x] `GET /api/jobs/{id}/download_sample`
- [x] `PATCH /api/jobs/{id}/kill`
- [x] `PATCH /api/jobs/{id}/analyzer/{nameOfAnalyzer}/kill`
- [x] `PATCH /api/jobs/{id}/analyzer/{nameOfAnalyzer}/retry`
- [x] `PATCH /api/jobs/{id}/connector/{nameOfConnector}/kill`
- [x] ` PATCH /api/jobs/{job_id}/connector/{name}/retry`

## Analysis
- [x] `POST /api/analyze_observable`
- [x] `POST /api/analyze_multiple_observables`
- [x] `POST /api/analyze_file`
- [x] ` POST /api/analyze_multiple_files`

## Me (User details)
- [x] `GET /api/me/access`
- [x] `GET /api/me/organization`
- [x] `POST /api/me/organization`
- [x] `POST /api/me/organization/invite`
- [x] `POST /api/me/organization/remove_member`

## Playbooks
- [ ] `GET /api/get_playbooks_config`
- [ ] `POST /api/playbook/analyse_observable`
- [ ] `POST /api/playbook/analyse_file`

**Comment by sp35** [comment]
Closing this as completed, https://github.com/intelowlproject/go-intelowl/issues/60 has been opened for playbook endpoints.
