### ISSUE TITLE
Basic project structure, gh action files, publish to https://pkg.go.dev/

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/go-intelowl#4]
Useful reference: https://golang.org/doc/tutorial/create-module

- Barebones go.mod, go.sum files
- basic project structure with proper documentation for the `IntelOwlClient` struct and it's functions which can be published to https://pkg.go.dev/.
- maybe some github actions/workflow files which publishes to pkg.go.dev ? (I lack knowledge here since I haven't published a go package before so any kind of help is appreciated)

**Comment by spiderxm** [comment]
Assign me this issue. I would to work on this.

**Comment by spiderxm** [comment]
Basic project structure and gh action files are added.

**Comment by fear-the-reaper** [comment]
Hi! can you tell me what I need to learn to do this issue? Thank you
