### ISSUE TITLE
Adding a Constants.go

### ISSUE THREAD

**Issue by fear-the-reaper** [intelowlproject/go-intelowl#41]
Like in Java we have `Constants` classes to keep all of your constants such as
1. Endpoints
2. Methods (GET, POST)
It would be a good approach to add this as it is much more manageable, and idiomatic.

**Comment by trupti2003** [comment]
What to write in constants.go file ?

**Comment by fear-the-reaper** [comment]
Basically writing all the endpoints in 1 file. There's a PR #45 already in review for it.
