### ISSUE TITLE
Avoid repeatition of package name in function/variable names.

### ISSUE THREAD

**Issue by its-me-debk007** [intelowlproject/go-intelowl#63]
Since while accessing any property of a package, the client will write the package name, so there is no need to include package name in the content name.

e.g. in the file client.go, we have a struct named IntelOwlClientOptions. Whenever the client needs to access it, he/she writes :-

`gointelowl.IntelOwlClientOptions{}`

Here, the word IntelOwl is repeating 2 times! Instead, we can write :-

`gointelowl.ClientOptions{}`

The names of the contents of the package must be renamed to follow the **conventions** and **avoid unneccessary long names**.

### Here is a screenshot from official golang blog

![WhatsApp Image 2022-11-03 at 16 45 27](https://user-images.githubusercontent.com/81604986/199707261-f492e780-afe2-4e5b-a8bd-34e13f15cedb.jpeg)

**Comment by its-me-debk007** [comment]
I would like to work on this issue & contribute to this repo

**Comment by sp35** [comment]
Thanks for pointing this out. I'm assigning you this issue.

**Comment by its-me-debk007** [comment]
should I also update the code for deprecated ioutil package in the file client.go?

![Screenshot from 2022-11-05 18-52-58](https://user-images.githubusercontent.com/81604986/200122202-5e221b66-523e-4fe5-bee0-44e746bedd2e.png)

**Comment by ashutosh887** [comment]
LEt me work on this @its-me-debk007 
Please assign

**Comment by mlodic** [comment]
hey @ashutosh887 you are welcome here! :) however we can't assign to you too many issues, just try to solve one issue at a time :)

**Comment by ashutosh887** [comment]
Sure @mlodic 
Works for me :)
Though it's great to get assigned and keep working on the go from issues tab from GitHub profile

**Comment by its-me-debk007** [comment]
I've actually completed working on this issue, and also raised a PR. But didn't got any further response!

**Comment by mlodic** [comment]
merged!

**Comment by its-me-debk007** [comment]
Thanks!
